project:
  type: website
  title: Value at Risk

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    number-sections: true
    #css: styles.css
    #html-math-method: katex
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    #embed-resources: true

website:
  title: "Portfolio Risk"
  favicon: "assets/favicon-32x32.png"
  open-graph: true
  repo-url: "https://github.com/EinMaulwurf/risk"
  repo-branch: main
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    #collapse-level: 1
    search: true
    tools:
      - icon: github
        href: "https://github.com/EinMaulwurf"
        text: "Github"
      # - icon: linkedin
      #   href: "https://linkedin.com/in/sebastian-geis-7a3383205"
      #   text: "LinkedIn"
    contents:
      - href: index.qmd
        text: "Overview"
      - href: src/methodology.qmd
        text: "Methodology"
      - href: src/case_study.qmd
        text: "Value-at-Risk Case Study"
      - href: src/volatility.qmd
        text: "Modelling Volatility"
      - href: src/risk_app.qmd
        text: "Interactive App"
