project:
  type: website
  title: Value at Risk

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    number-sections: true
    #css: styles.css
    #html-math-method: katex
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    #embed-resources: true

website:
  title: "Portfolio Risk"
  #repo-url: "https://github.com/andrewheiss/ath-quarto"
  sidebar:
    style: "docked"
    #collapse-level: 1
    search: true
    contents:
      - href: index.qmd
        text: "Overview"
      - href: src/methodology.qmd
        text: "Methodology"
      - href: src/case_study.qmd
        text: "Case Study"
      - href: src/risk_app.qmd
        text: "Interactive App"
